# AIRBNB code style : https://github.com/airbnb/javascript

env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: [ ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  react/prop-types: off
  react/function-component-definition: off
  max-len: off
  object-curly-newline: off
